### PR TITLE
add a check for "extra" arguments clashing with default LogRecord fields

### LINKED ISSUE #17: Check when extra in log override default fields
When passed to logger extra parameters overwrite default logging fields like `name`, `lineno` or `message`, logging raises KeyError exception at runtime. It will be very useful to find out this at static checks stage.

Example:

```python
import logging
logging.warning('msg', extra=dict(name='test'))
```

This raises next exception:
```python
KeyError: "Attempt to overwrite 'name' in LogRecord"
```

### PR DESCRIPTION
**Pull request by si14**
Resolves #17

### CODE REVIEW

**Comment by jameschung2019** [comment]
Hey there, please close this PR or merge it appropriately. It will be auto-closed in 48 hours if not acted upon.

If you decide to merge it, comment here and take ownership to coordinate, schedule, and get it done. Thanks!

**Comment by si14** [comment]
Hey!

It was merging fine when I've sent the PR, I'll merge against master in a few days.

**Comment by si14** [comment]
Oh sorry, I was seeing that big red cross and didn't realise what it's saying next to it. Apparently it can be clearly merged already if someone approves it.

**Comment by si14** [comment]
Thanks for merging this!

By the way, is there a chance you can cut a release with this PR?

**Pull request merged**
